name: Terraform Demo Plan

on:
  pull_request:

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  TF_VAR_pub_key: "${{ secrets.PUB_KEY }}"
  TF_VAR_admin_password: "${{ secrets.PZ_ADMIN }}"
  TF_VAR_server_password: "${{ secrets.PZ_SERVER }}"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_CLOUD }}
          terraform_version: 1.13.3

      - name: Create backend config
        id: backend
        run: |
          touch config.remote.tfbackend
          echo "${{ vars.BACKEND }}" > config.remote.tfbackend

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=config.remote.tfbackend

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
